// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8qzCb6Qf06WMQmkQhhL-s8p84NH-esU',
    appId: '1:477203020532:android:82ca38abad33a4993abca1',
    messagingSenderId: '477203020532',
    projectId: 'ffff-4d4b8',
    databaseURL: 'https://ffff-4d4b8-default-rtdb.firebaseio.com',
    storageBucket: 'ffff-4d4b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kJkgD8bwkYRcGaiFa0Etd6YASbWqjRY',
    appId: '1:477203020532:ios:9a4b4ff9eb8c518f3abca1',
    messagingSenderId: '477203020532',
    projectId: 'ffff-4d4b8',
    databaseURL: 'https://ffff-4d4b8-default-rtdb.firebaseio.com',
    storageBucket: 'ffff-4d4b8.appspot.com',
    androidClientId: '477203020532-3qfui2ap80f3il21sl8q0u6b303urp2c.apps.googleusercontent.com',
    iosClientId: '477203020532-2k15eor5gk57ub83a0ocvdj9vdkefpo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanagementRavi',
  );
}
